# Generated by Django 5.1.1 on 2024-09-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bookHouse.bookshelf', verbose_name='Книжная полка'),
        ),
    ]
