# Generated by Django 5.1.1 on 2024-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHouse', '0002_book_book_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Дата издания'),
        ),
    ]
