# Generated by Django 5.1.1 on 2024-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHouse', '0003_alter_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movebookjournal',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Книга возвращена'),
        ),
    ]
